### ISSUE TITLE
Updating `keycloak_default_extension` wont delete jar file

### ISSUE THREAD

**Issue by schoggobaer** [rolehippie/keycloak#12]
Hello,

when i update an extension then the jar file wont be updated.

Update keycloak metrics from 2.0.0 to 5.0.0. 
The file under `/usr/share/keycloak/extensions` wont be updated. i have to delete it manually

f.e.
```
keycloak_default_extensions:
  - name: keycloak-metrics-spi
    url: https://github.com/aerogear/keycloak-metrics-spi/releases/download/5.0.0/keycloak-metrics-spi-5.0.0.jar
```

**Comment by tboerger** [comment]
I have integrated different possible solutions. First of all you are able to add a `checksum` to the extension list which ensures that the file to download matches the already existing file which should replace the file for new versions, see https://github.com/rolehippie/keycloak/commit/56ca31f4ed1bdb75df6d3c406da4c6573f5ffed5 for reference. Beside that I have changed the list of default extensions. It is deleting the old `keycloak-metrics-spi.jar` and downloads the defined version from `keycloak_metrics_extension_version` to the file name including the version. That way you are always able to remove the older extensions by adding `name: keycloak-metrics-spi-x.x.x.jar` and `state: absent` to the list of extensions. You can see the details at https://github.com/rolehippie/keycloak/commit/a6a1491319525df8dc6c0ffe2255acfce0f921f8
